---
apiVersion: v1
kind: Service
metadata:
  name: dns-lb-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: opendns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
  loadBalancerIP: 172.17.255.5

---
apiVersion: v1
kind: Service
metadata:
  name: dns-lb-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: opendns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  loadBalancerIP: 172.17.255.5
