apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    webserver: nginx
spec:
  containers:
  - name: web
    image: zdeniz/otus-webapp:1.0
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: "init"
    image: "busybox:1.31.0"
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
